[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"
  
[build]
  publish = "docs/.vitepress/dist"
  command = "npx pnpm@7.8.0 i --store=node_modules/.pnpm-store --no-frozen-lockfile && npm run docs:build"